### ISSUE TITLE
Support imports

### ISSUE THREAD

**Issue by combmag** [yibn2008/fast-sass-loader#43] opened 2018-09-28 07:18 UTC
Hi i'm trying to use fast-sass-loader in favor of sass-loader

Currently sass-loader support imports using an alias: https://github.com/webpack-contrib/sass-loader#imports

Example:

```
// file.scss
@import ~custom-palette
```
webpack.config.js
```
alias: {
    '$custom-palette': path.resolve(__dirname, "./mycustom-palette.scss")
}
```

is this something that fast-sass-loader supports? since i didn't manage to find any docs

**Comment by Steven0811** [comment] 2018-10-25 09:54
+1

**Comment by j1wilmot** [comment] 2018-12-12 21:19
Duplicate of #40 and #39

**Comment by DanielRuf** [comment] 2019-02-24 21:49
Did you already test `includePaths`?

**Comment by yibn2008** [comment] 2019-02-26 07:57
I've test with these code:

```scss
@import "~$custom-palette";
```

```js
resolve: {
    alias: {
      '$custom-palette': path.resolve(__dirname, "./mycustom-palette.scss")
    },
  },
```

and it works. please provide a demo to reproduce this problem.

**Closed** 2019-02-26 07:58 UTC
