### ISSUE TITLE
Wrong path converted in Windows environment.

### ISSUE THREAD

**Issue by aj120426394** [yibn2008/fast-sass-loader#5] opened 2017-03-26 23:52 UTC
Hi yibn2008,

I got a issues with a setup like this:
```
const devServerPort = 8100;
const extractCSS =  new ExtractTextPlugin('[name].[chunkhash].css');
const config = {
      context: this.context,
      entry: {app: 'index.js'},
      output: {
        path: path.resolve(__dirname, 'dist'),
        publicPath: env === 'development' ? `http://localhost:${devServerPort}/` : this.publicPath,
        filename: '[name].[hash].js',
        chunkFilename: '[name].[chunkhash:8].js'
      },
      resolve: {
        extensions: ['.js', '.jsx'],
        modules: ['node_modules', '/app/vendors'],
        alias: {}
      },
      profile: true,
      cache: true,
      module: {
        rules: [
          {
            test: /\.jsx?$/,
            use: [
              {
                loader: 'babel-loader'
              }
            ],
            exclude: /(node_modules|bower_components|vendors)/
          }, {
            test: /\.jsx?$/,
            use: [
              {
                loader: 'babel-loader'
              }
            ],
            include: /estoolbox/
          }, {
            test: /\.scss$/,
            loader: extractCSS.extract({
                fallback: 'style-loader,
                loader: [
                    {loader: 'css-loader'},
                    {loader: 'fast-sass-loader'}
                ]
            })
          }, {
            test: /\.(ttf|otf|eot|svg|woff(2)?)(\?v=\d+\.\d+\.\d+)?$/,
            loader: 'file-loader',
            options: {
              name: '[path][name].[ext]'
            },
            exclude: /(node_modules|bower_components|vendors)/
          }, {
            test: /\.(ttf|otf|eot|svg|woff(2)?)(\?v=\d+\.\d+\.\d+)?$/,
            loader: 'file-loader',
            options: {
              name: '/assets/fonts/vendor/[name].[ext]'
            },
            include: /(node_modules|bower_components|vendors)/
          }, {
            test: /\.htaccess$/,
            loader: 'file-loader',
            options: {
              name: '/fonts/[name].[ext]'
            }
          }, {
            test: /\.(jpg|JPG|png|gif)$/,
            loader: 'file-loader',
            options: {
              name: '[path][name].[ext]'
            },
            exclude: /(node_modules|bower_components|vendors)/
          }, {
            test: /\.(jpg|JPG|png|gif)$/,
            loader: 'file-loader',
            options: {
              name: '/assets/images/vendor/[name].[ext]'
            },
            include: /(node_modules|bower_components|vendors)/
          }, {
            test: /\.hbs$/,
            loader: 'handlebars-loader'
          }, {
            test: /\.html$/,
            loader: 'html-loader'
          }]
      },
      plugins: [
        new HtmlWebpackPlugin({
           template: './index.html'
       }),
        new webpack.NamedModulesPlugin(),
        extractCSS
      ]
    }
```
and the part of the source code with issue is this:
```
.hello {
  color: yellow;
  background-image: url("../../assets/images/BITHM_Module00_Background.jpg");
}
```

The issues is that when I apply this configuration in MacOS environment, everything works fine. But when I was using this configuration under Windows environment, it pops error like this:
```
ERROR in ../~/css-loader!../~/fast-sass-loader/lib!./scss/app.scss
Module not found: Error: Can't resolve './../assetsimages♂ITHM_Module00_Background.jpg' in 'D:\Git\npm-webpack2\app\scss'
 @ ../~/css-loader!../~/fast-sass-loader/lib!./scss/app.scss 2:249947-250009
 @ ./scss/app.scss
 @ ./js/index.js
 @ multi ./js/index.js
```
Seems that under the Windows environment, it couldn't read the background images path right. If you see through the error, you can see that there is '/' missing. Some of it just disappear and some of it be convert in to a weird symbol '♂'. However, when I was using sass-laoder + resolve-url-loader, it works in both environment.

Please let me know if there is anything wrong in my configuration or any solution for this, thank you!

**Comment by andersekdahl** [comment] 2017-04-04 13:24
We're seeing this as well. It's because `fast-sass-loader` verifies the path with `path` but the path on Windows will contain backslashes. The path should only contain regular slashes.

We're also seeing that it tries to replace `url('!!file!./some/path/to/file.ext')` incorrectly, it sees `!!file!` as part of the file path.

**Comment by faddee** [comment] 2017-04-04 20:19
The missing characters seems to be fixed in v1.2.2. But I'm also having trouble with loaders like `url('raw-loader!./path/to/file.txt')`.

**Comment by yibn2008** [comment] 2017-04-05 04:05
@aj120426394 windows path issue should be fixed, but since I don't have any actual test case, I'm not sure if your problem has been solved. You can upgrade to 1.2.3 to try it, if the problem still exists, please let me know, and *any demo project can reproduce this issue will be helpful*.

**Comment by yibn2008** [comment] 2017-04-05 04:11
@andersekdahl @faddee I have handled the inline loader case `url("<loader>!<file>")` in fast-sass-loader@1.2.3, you can try it.

Again, if the problem still exists, please provide a demo project to help me locate it.

**Closed** 2017-04-05 04:11 UTC

**Comment by faddee** [comment] 2017-04-05 05:39
@yibn2008 Thanks a lot!

**Comment by aj120426394** [comment] 2017-04-11 02:47
Problem solved, thank you.
